Global:
  use_gpu: true
  epoch_num: 72 # modify
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/ic15/
  save_epoch_step: 3
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model: ./pretrain_models/MobileNetV3_large_x0_5_pretrained.pdparams # modify
  checkpoints:
  save_inference_dir: ./
  use_visualdl: True # modify
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path: ./train_data/ccpd19/rec/word_dict.txt # modify
  max_text_length: 7 # modify,绿牌车的车牌长度为7
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_ic15.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005 # modify
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
#    data_dir: ./train_data/ic15_data/
    data_dir: ./train_data/ccpd19/rec/
    label_file_list: ["./train_data/ccpd19/rec/train_rec.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 170 # modify
    drop_last: True
    num_workers: 8 # modify
    use_shared_memory: False

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/ccpd19/rec/ # modify
    label_file_list: ["./train_data/ccpd19/rec/val_rec.txt"] # modify
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 25 # modify
    num_workers: 4
    use_shared_memory: False
